### ISSUE TITLE
Create a new release with Makefile

### ISSUE THREAD

**Issue by toml01** [jergusg/k380-function-keys-conf#12]
Hey, great repo helped me a lot, thanks!

In the readme there are instructions to use the Makefile for installation, but you also say:
> Download installation files https://github.com/jergusg/k380-function-keys-conf/releases/ (Source code).

But the only release is pretty old and does not include the Makefile.
Can you make a new release with the Makefile?

**Comment by jergusg** [comment]
Thank you, I did update the release
