### ISSUE TITLE
Do you know how to auto on when k380 bluetooth connected

### ISSUE THREAD

**Issue by ohmerhe** [jergusg/k380-function-keys-conf#4]
Do you know how to auto on when k380 bluetooth connected

**Comment by bogdan-bodnaruk** [comment]
The same question. Using Ubuntu 16.04 and did everything as described in the build.js. It works but does not applies by default when the keyboard is connected

**Comment by bogdan-bodnaruk** [comment]
So, I was able to resolve it. Probably it makes sense to add it to the readme file.
First, you need to copy the rules file into the correct folder. 
`sudo cp 80-k380.rules /etc/udev/rules.d/80-k380.rules`

After that, run two commands to refresh your configs.
```sh
sudo udevadm control --reload-rules
sudo udevadm trigger --subsystem-match=input
```
It started to work as expected after that.

**Comment by ohmerhe** [comment]
Great, it works fine.
Thank you.

**Comment by kongdd** [comment]
Just wondering where can I find the file of `80-k380.rules`?
